import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Badge } from "../Components/Badge/Badge";
import { Button } from "../Components/Buttons/Button";
import { ImageCard } from "../Components/Cards/ImageCard";
import { SimpleCard } from "../Components/Cards/SimpleCard";
import { SimpleCardWD } from "../Components/Cards/SimpleCardWD";
import { FacebookIcon } from "../Components/Icons/FacebookIcon";
import { InstagramIcon } from "../Components/Icons/InstagramIcon";
import { TwitterIcon } from "../Components/Icons/TwitterIcon";
import { YoutubeIcon } from "../Components/Icons/YoutubeIcon";
import { Line } from "../Components/Line/Line";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <h1 className="text-3xl font-oswald">
          Các bệnh hô hấp thường gặp khi trời trở lạnh
        </h1>
        <h1 className="text-3xl font-bold underline font-roboto">
          Các bệnh hô hấp thường gặp khi trời trở lạnh
        </h1>
        <FacebookIcon />
        <TwitterIcon />
        <InstagramIcon />
        <YoutubeIcon />
        {/* <span className="bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 dark:bg-blue-200 dark:text-blue-800">
          Default
        </span> */}
        <Badge text={"All"} color={"bg-primary"} />
        <Badge text={"Football"} color={"bg-light-purple"} />
        <Badge text={"Cricket"} color={"bg-light-green"} />
        <Badge text={"Baseketball"} color={"bg-light-blue"} />
        <Line />
        <SimpleCard />
        <SimpleCard />
        <SimpleCard />
        <SimpleCard />
        <SimpleCardWD />
        <ImageCard />
        <Button />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
